drill_bit_size = 5 + 0.1
sheet_thickness = 18
screw_hole_r = 2/2
box2shelf_spacing = 1
drawer_box_size_outer = (300, 450, 80)
drawer_shelf_size = (
    drawer_box_size_outer[0] + box2shelf_spacing * 2 + sheet_thickness * 2,
    drawer_box_size_outer[1] + box2shelf_spacing * 2 + sheet_thickness * 2,
)
joint_a_width = 40
